export const data = [
    {
        name: "watermelon",
        description: "juicy watermelon from japan, this is the watermelon you always wanted, crunchy, tasty and sugar free. 12 popsicles.",
        price: 20,
        nutrition: [
            {label: "calories", value: 40, measure: "",percentage: 0},
            {label: "total fat", value: 0, measure: "g",percentage: 0},
            {label: "saturated fat", value: 0, measure: "g",percentage: 0},
            {label: "trans fat", value: 0, measure: "g",percentage: 0},
            {label: "cholesterol", value: 0, measure: "mg",percentage: 0},
            {label: "sodium", value: 0, measure: "mg",percentage: 0},
            {label: "total carbohydrate", value: 9, measure: "g",percentage: 0},
            {label: "dietary fiber", value: 1, measure: "g",percentage: 0},
            {label: "total sugars", value: 6, measure: "g",percentage: 0},
            {label: "added sugar", value: 0, measure: "g",percentage: 0},
            {label: "protein", value: 0, measure: "g",percentage: 0},
            {label: "vitamin d", value: 0, measure: "mcg",percentage: 0},
            {label: "calcium", value: 3, measure: "mg",percentage: 0},
            {label: "iron", value: 0, measure: "mg",percentage: 0},
            {label: "potassium", value: 64, measure: "mg",percentage: 0},
        ]
    },
    {
        name: "grapefruit",
        description: "grapefruit from vietnam, ripe and always fresh the best flavour, crunchy, tasty and sugar free. 12 popsicles.",
        price: 20,
        nutrition: [
            {label: "calories", value: 40, measure: "",percentage: 0},
            {label: "total fat", value: 0, measure: "g",percentage: 0},
            {label: "saturated fat", value: 0, measure: "g",percentage: 0},
            {label: "trans fat", value: 0, measure: "g",percentage: 0},
            {label: "cholesterol", value: 0, measure: "mg",percentage: 0},
            {label: "sodium", value: 0, measure: "mg",percentage: 0},
            {label: "total carbohydrate", value: 9, measure: "g",percentage: 0},
            {label: "dietary fiber", value: 1, measure: "g",percentage: 0},
            {label: "total sugars", value: 6, measure: "g",percentage: 0},
            {label: "added sugar", value: 0, measure: "g",percentage: 0},
            {label: "protein", value: 0, measure: "g",percentage: 0},
            {label: "vitamin d", value: 0, measure: "mcg",percentage: 0},
            {label: "calcium", value: 3, measure: "mg",percentage: 0},
            {label: "iron", value: 0, measure: "mg",percentage: 0},
            {label: "potassium", value: 64, measure: "mg",percentage: 0},
        ]
    },
    {
        name: "strawberry",
        description: "one of the most wanted, fresh strawberries from mexico ready to explode in your mouth, crunchy, tasty and sugar free. 12 popsicles.",
        price: 15.99,
        nutrition: [
            {label: "calories", value: 40, measure: "",percentage: 0},
            {label: "total fat", value: 0, measure: "g",percentage: 0},
            {label: "saturated fat", value: 0, measure: "g",percentage: 0},
            {label: "trans fat", value: 0, measure: "g",percentage: 0},
            {label: "cholesterol", value: 0, measure: "mg",percentage: 0},
            {label: "sodium", value: 0, measure: "mg",percentage: 0},
            {label: "total carbohydrate", value: 9, measure: "g",percentage: 0},
            {label: "dietary fiber", value: 1, measure: "g",percentage: 0},
            {label: "total sugars", value: 6, measure: "g",percentage: 0},
            {label: "added sugar", value: 0, measure: "g",percentage: 0},
            {label: "protein", value: 0, measure: "g",percentage: 0},
            {label: "vitamin d", value: 0, measure: "mcg",percentage: 0},
            {label: "calcium", value: 3, measure: "mg",percentage: 0},
            {label: "iron", value: 0, measure: "mg",percentage: 0},
            {label: "potassium", value: 64, measure: "mg",percentage: 0},
        ]
    },
    {
        name: "kiwi",
        description: "come and experiment, the new kiwi from asia flavour, an exciting and epic flavour, crunchy, tasty and sugar free. 12 popsicles.",
        price: 20,
        nutrition: [
            {label: "calories", value: 40, measure: "",percentage: 0},
            {label: "total fat", value: 0, measure: "g",percentage: 0},
            {label: "saturated fat", value: 0, measure: "g",percentage: 0},
            {label: "trans fat", value: 0, measure: "g",percentage: 0},
            {label: "cholesterol", value: 0, measure: "mg",percentage: 0},
            {label: "sodium", value: 0, measure: "mg",percentage: 0},
            {label: "total carbohydrate", value: 9, measure: "g",percentage: 0},
            {label: "dietary fiber", value: 1, measure: "g",percentage: 0},
            {label: "total sugars", value: 6, measure: "g",percentage: 0},
            {label: "added sugar", value: 0, measure: "g",percentage: 0},
            {label: "protein", value: 0, measure: "g",percentage: 0},
            {label: "vitamin d", value: 0, measure: "mcg",percentage: 0},
            {label: "calcium", value: 3, measure: "mg",percentage: 0},
            {label: "iron", value: 0, measure: "mg",percentage: 0},
            {label: "potassium", value: 64, measure: "mg",percentage: 0},
        ]
    }
]